package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
)

type item struct {
	Text     string   `json:"text"`
	Subitems []string `json:"subitems"`
}

type subsection struct {
	Heading *string `json:"heading"`
	Items   []item  `json:"items"`
}

type section struct {
	Name        string       `json:"name"`
	Subsections []subsection `json:"subsections"`
}

type entry struct {
	Version  string    `json:"version"`
	Date     string    `json:"date"`
	Sections []section `json:"sections"`
}

var (
	versionRe    = regexp.MustCompile(`^## \[(.+?)\] - (.+)$`)
	sectionRe    = regexp.MustCompile(`^### (.+)$`)
	subheadingRe = regexp.MustCompile(`^#### (.+)$`)
	subitemRe    = regexp.MustCompile(`^  - (.+)$`)
	itemRe       = regexp.MustCompile(`^- (.+)$`)
)

func flushItem(cur **item, sub **subsection) {
	if *cur == nil || *sub == nil {
		return
	}
	(*sub).Items = append((*sub).Items, **cur)
	*cur = nil
}

func flushSubsection(sub **subsection, sec **section) {
	if *sub == nil || *sec == nil {
		return
	}
	(*sec).Subsections = append((*sec).Subsections, **sub)
	*sub = nil
}

func flushSection(sec **section, e **entry) {
	if *sec == nil || *e == nil {
		return
	}
	(*e).Sections = append((*e).Sections, **sec)
	*sec = nil
}

func parse(path string) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []entry
	var current *entry
	var currentSection *section
	var currentSubsection *subsection
	var currentItem *item

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		if m := versionRe.FindStringSubmatch(line); m != nil {
			flushItem(&currentItem, &currentSubsection)
			flushSubsection(&currentSubsection, &currentSection)
			flushSection(&currentSection, &current)
			if current != nil {
				entries = append(entries, *current)
			}
			current = &entry{Version: m[1], Date: strings.TrimSpace(m[2])}
			continue
		}

		if m := sectionRe.FindStringSubmatch(line); m != nil {
			if current == nil {
				continue
			}
			flushItem(&currentItem, &currentSubsection)
			flushSubsection(&currentSubsection, &currentSection)
			flushSection(&currentSection, &current)
			currentSection = &section{Name: m[1]}
			continue
		}

		if m := subheadingRe.FindStringSubmatch(line); m != nil {
			if currentSection == nil {
				continue
			}
			flushItem(&currentItem, &currentSubsection)
			flushSubsection(&currentSubsection, &currentSection)
			h := m[1]
			currentSubsection = &subsection{Heading: &h, Items: []item{}}
			continue
		}

		if m := subitemRe.FindStringSubmatch(line); m != nil {
			if currentItem == nil {
				continue
			}
			currentItem.Subitems = append(currentItem.Subitems, m[1])
			continue
		}

		if m := itemRe.FindStringSubmatch(line); m != nil {
			if currentSection == nil {
				continue
			}
			if currentSubsection == nil {
				currentSubsection = &subsection{Heading: nil, Items: []item{}}
			}
			flushItem(&currentItem, &currentSubsection)
			currentItem = &item{Text: m[1], Subitems: []string{}}
			continue
		}
	}

	flushItem(&currentItem, &currentSubsection)
	flushSubsection(&currentSubsection, &currentSection)
	flushSection(&currentSection, &current)
	if current != nil {
		entries = append(entries, *current)
	}

	return entries, scanner.Err()
}

func write(path string, entries []entry) error {
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return err
	}

	content := fmt.Sprintf(`// Auto-generated by scripts/generate-changelog/main.go — do not edit manually.
// Run: mise run generate:changelog

export interface ChangelogItem {
  text: string;
  subitems: string[];
}

export interface ChangelogSubsection {
  heading: string | null;
  items: ChangelogItem[];
}

export interface ChangelogSection {
  name: string;
  subsections: ChangelogSubsection[];
}

export interface ChangelogEntry {
  version: string;
  date: string;
  sections: ChangelogSection[];
}

export const CHANGELOG: ChangelogEntry[] = %s;
`, string(data))

	return os.WriteFile(path, []byte(content), 0o644)
}

func main() {
	entries, err := parse("CHANGELOG.md")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading CHANGELOG.md: %v\n", err)
		os.Exit(1)
	}

	if err := write("frontend/src/generated/changelog.ts", entries); err != nil {
		fmt.Fprintf(os.Stderr, "error writing changelog.ts: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated changelog.ts with %d entries\n", len(entries))
}
