package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
)

type section struct {
	Name  string   `json:"name"`
	Items []string `json:"items"`
}

type entry struct {
	Version  string    `json:"version"`
	Date     string    `json:"date"`
	Sections []section `json:"sections"`
}

var (
	versionRe = regexp.MustCompile(`^## \[(.+?)\] - (.+)$`)
	sectionRe = regexp.MustCompile(`^### (.+)$`)
	itemRe    = regexp.MustCompile(`^- (.+)$`)
)

func parse(path string) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []entry
	var current *entry
	var currentSection *section

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		if m := versionRe.FindStringSubmatch(line); m != nil {
			if current != nil {
				if currentSection != nil {
					current.Sections = append(current.Sections, *currentSection)
					currentSection = nil
				}
				entries = append(entries, *current)
			}
			current = &entry{Version: m[1], Date: strings.TrimSpace(m[2])}
			continue
		}

		if m := sectionRe.FindStringSubmatch(line); m != nil {
			if current == nil {
				continue
			}
			if currentSection != nil {
				current.Sections = append(current.Sections, *currentSection)
			}
			currentSection = &section{Name: m[1]}
			continue
		}

		if m := itemRe.FindStringSubmatch(line); m != nil {
			if currentSection == nil {
				continue
			}
			currentSection.Items = append(currentSection.Items, m[1])
		}
	}

	if current != nil {
		if currentSection != nil {
			current.Sections = append(current.Sections, *currentSection)
		}
		entries = append(entries, *current)
	}

	return entries, scanner.Err()
}

func write(path string, entries []entry) error {
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return err
	}

	content := fmt.Sprintf(`// Auto-generated by scripts/generate-changelog/main.go — do not edit manually.
// Run: mise run generate:changelog

export interface ChangelogSection {
  name: string;
  items: string[];
}

export interface ChangelogEntry {
  version: string;
  date: string;
  sections: ChangelogSection[];
}

export const CHANGELOG: ChangelogEntry[] = %s;
`, string(data))

	return os.WriteFile(path, []byte(content), 0o644)
}

func main() {
	entries, err := parse("CHANGELOG.md")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading CHANGELOG.md: %v\n", err)
		os.Exit(1)
	}

	if err := write("frontend/src/generated/changelog.ts", entries); err != nil {
		fmt.Fprintf(os.Stderr, "error writing changelog.ts: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated changelog.ts with %d entries\n", len(entries))
}
