// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile():Promise<main.OpenFileResult>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<string>;

export function SaveImageAs(arg1:string):Promise<string>;

export function SaveImageAs(arg1:string):Promise<string>;
