// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function ExportData(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ImportData():Promise<string>;
